# nixpacks.toml

[phases.install]
  cmds = ["pip install -r requirements.txt"]

[phases.playwright]
  dependsOn = ["install"]
  cmds = ["playwright install --with-deps"]

[start]
cmd = "gunicorn app:webui"
