# nixpacks.toml



[phases.install]
  cmds = ["pip install -r requirements.txt"]

[phases.chromium]
  dependsOn = ["install"]
  cmds = ["playwright install --with-deps chromium"]

[start]
cmd = "gunicorn app:webui"
